/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Currency;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author thanh
 */
public class formBanHang extends javax.swing.JInternalFrame {
    public Connection conn;
    public PreparedStatement ps = null;
    public ResultSet rs = null;
    DefaultTableModel dtm;
    /**
     * Creates new form formBanHang
     */
    public formBanHang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI UI=(BasicInternalFrameUI)this.getUI();
        UI.setNorthPane(null);
        KetNoiCSDL();
        dtm = (DefaultTableModel) tblHoaDon.getModel();
        HienThiCboTenLinhKien();
        HienThiCboNhanVien();
        HienThiCboKhachHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboTenLK = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        cboTenNV = new javax.swing.JComboBox<>();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaLK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        cboTenKH = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnXoaSP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1396, 928));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel9.setText("BÁN HÀNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Tên Nhân Viên");

        cboTenLK.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cboTenLK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTenLKItemStateChanged(evt);
            }
        });
        cboTenLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTenLKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboTenLKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cboTenLKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboTenLKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cboTenLKMouseReleased(evt);
            }
        });
        cboTenLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenLKActionPerformed(evt);
            }
        });
        cboTenLK.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboTenLKPropertyChange(evt);
            }
        });
        cboTenLK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboTenLKKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Tên Linh Kiện");

        btnThem.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cboTenNV.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txtGiaBan.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtGiaBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGiaBanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Gía Bán");

        txtMaLK.setEditable(false);
        txtMaLK.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Tên Khách Hàng");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText("Mã Linh Kiện");

        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyPressed(evt);
            }
        });

        cboTenKH.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        cboTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenKHActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("Số Lượng");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Thành Tiền");

        txtThanhTien.setEditable(false);
        txtThanhTien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboTenKH, javax.swing.GroupLayout.Alignment.LEADING, 0, 214, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(43, 43, 43)
                                        .addComponent(cboTenLK, 0, 210, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(46, 46, 46)
                                        .addComponent(txtMaLK)))))))
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(cboTenLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnXoaSP.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnXoaSP.setText("Xóa Sản Phẩm");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Tổng Tiền: ");

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        btnThanhToan.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnInHoaDon.setText("In Hóa Đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaSP)
                        .addGap(18, 18, 18)
                        .addComponent(btnInHoaDon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblHoaDon.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Linh Kiện", "Mã Linh Kiện", "Gía Bán", "Số Lượng", "Thành Tiền"
            }
        ));
        tblHoaDon.setRowHeight(40);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection KetNoiCSDL() {
        String user = "sa";
        String pass = "123456";
        try {
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLLinhKienPC_Laptop_java", user, pass);

            return conn;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return conn;
    }
    
    public void HienThiCboTenLinhKien() {
        try {
            conn = KetNoiCSDL();
            String sql = "select TenLinhKien from LinhKien where DaXoa=0";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            cboTenLK.removeAllItems();
            while (rs.next()) {
                cboTenLK.addItem(rs.getString("TenLinhKien"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void HienThiCboNhanVien() {
        try {
            // conn=KetNoiCSDL();
            String sql = "select HoTen from NHANVIEN where DaXoa=0";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            cboTenNV.removeAllItems();
            while (rs.next()) {
                cboTenNV.addItem(rs.getString("HoTen"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void HienThiCboKhachHang() {
        try {
            //conn=KetNoiCSDL();
            String sql = "select HoTen from KHACHHANG where DaXoa=0";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            cboTenKH.removeAllItems();
            while (rs.next()) {
                cboTenKH.addItem(rs.getString("HoTen"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private int LayMaKhachHangTheoTen(String TenKH) {
        int Ma = 0;
        try {
            //conn=KetNoiCSDL();
            String sql = "select MaKhachHang from KHACHHANG where DaXoa=0 and Hoten=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, TenKH);
            rs = ps.executeQuery();
            while (rs.next()) {
                Ma = rs.getInt("MaKhachHang");
                return Ma;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // xong gán nó cho thằng mã này
        return Ma;
    }

    private int LayMaNhanVienTheoTen(String TenNV) {
        int Ma = 0;
        try {
            //conn=KetNoiCSDL();
            String sql = "select MANV from NHANVIEN where DaXoa=0 and HoTen=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, TenNV);
            rs = ps.executeQuery();
            while (rs.next()) {
                Ma = rs.getInt("MANV");
                return Ma;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // xong gán nó cho thằng mã này
        return Ma;
    }

    private int LayMaLinhKienTheoTen(String TenLinhKien) {
        int Ma = 0;
        try {
            conn = KetNoiCSDL();
            String sql = "select MaLinhKien from LinhKien where DaXoa=0 and TenLinhKien=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, TenLinhKien);
            rs = ps.executeQuery();
            while (rs.next()) {
                Ma = rs.getInt("MaLinhKien");
                return Ma;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // xong gán nó cho thằng mã này
        return Ma;
    }

    void hienThiThongTinSauKhiChonSanPham(String tenLK) {
        try {
            conn = KetNoiCSDL();
            String sql = "select MaLinhKien,GiaBan from LinhKien where TenLinhKien=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, tenLK);
            rs = ps.executeQuery();
            while (rs.next()) {
                txtGiaBan.setText(rs.getString("GiaBan"));
                txtMaLK.setText(rs.getString("MaLinhKien"));
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void themHoaDon(int maKH, int maNV, long tongTien) {
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        String date1 = formatter.format(date).toString();
        try {
            conn = KetNoiCSDL();
            String sql = "insert into HOADON(MANV,MaKhachHang,NgayXuatHoaDon,Tongtien,DaXoa)\n"
                    + "values(?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, maNV);
            ps.setInt(2, maKH);
            ps.setString(3, date1);
            ps.setLong(4, tongTien);
            ps.setInt(5, 0);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int layMaHoaDon() {
        int ma = 0;
        try {
            conn = KetNoiCSDL();
            String sql = "select top 1 MaHoaDon from HOADON order by MaHoaDon desc";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                ma = rs.getInt("MaHoaDon");
                return ma;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ma;
    }

    private void themCTHD(int maHD, int maLK, String tenLK, long giaBan, int soLuong, long thanhTien) {
        try {
            conn = KetNoiCSDL();
            String sql = "insert into CTHD(MaHoaDon,MaLinhKien,TenLinhKien,GiaBan,SoLuong,ThanhTien)\n"
                    + "values(?,?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, maHD);
            ps.setInt(2, maLK);
            ps.setString(3, tenLK);
            ps.setLong(4, giaBan);
            ps.setInt(5, soLuong);
            ps.setLong(6, thanhTien);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private long tinhTongTien() {
        long tongtien = 0;
        int row = tblHoaDon.getRowCount();
        for (int i = 0; i < row; i++) {
            long ThanhTien = Long.parseLong(tblHoaDon.getValueAt(i, 4).toString());
            tongtien += ThanhTien;
        }
        return tongtien;
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtSoLuong.getText().equals("") || txtGiaBan.getText().equals("")
            || txtMaLK.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin");
            return;
        }
        try {
            int slban = Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
            return;
        }
        try {
            long giaban = Long.parseLong(txtGiaBan.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gía bán phải là số");
            return;
        }

        int slban = Integer.parseInt(txtSoLuong.getText());
        long giaban = Long.parseLong(txtGiaBan.getText());
        long thanhTien = slban * giaban;
        int row = tblHoaDon.getRowCount();

        for (int i = 0; i < row; i++) {

            if (tblHoaDon.getValueAt(i, 1).equals(txtMaLK.getText())) {
                int slHienTai = Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString());
                int slThem = Integer.parseInt(txtSoLuong.getText());

                int tongSL = slHienTai + slThem;
                long thanhTienMoi = giaban * tongSL;
                long giaBanMoi = Long.parseLong(txtGiaBan.getText());

                tblHoaDon.setValueAt(giaBanMoi + "", i, 2);
                tblHoaDon.setValueAt(tongSL + "", i, 3);
                tblHoaDon.setValueAt(thanhTienMoi + "", i, 4);

                txtGiaBan.setText("");
                txtSoLuong.setText("");
                txtMaLK.setText("");
                txtThanhTien.setText("");

                long tongTien = tinhTongTien();
                Locale VN = new Locale("vi", "VN");
                Currency dollars = Currency.getInstance(VN);
                NumberFormat VNDFormat = NumberFormat.getCurrencyInstance(VN);
                txtTongTien.setText(VNDFormat.format(tongTien));
                return;

            }

        }
        Vector<Object> vec = new Vector<>();
        vec.add(cboTenLK.getSelectedItem().toString());
        vec.add(txtMaLK.getText());
        vec.add(txtGiaBan.getText());
        vec.add(txtSoLuong.getText());
        vec.add(thanhTien + "");
        dtm.addRow(vec);

        txtGiaBan.setText("");
        txtSoLuong.setText("");
        txtMaLK.setText("");
        txtThanhTien.setText("");

        long tongTien = tinhTongTien();
        Locale VN = new Locale("vi", "VN");
        Currency dollars = Currency.getInstance(VN);
        NumberFormat VNDFormat = NumberFormat.getCurrencyInstance(VN);
        txtTongTien.setText(VNDFormat.format(tongTien));
    }//GEN-LAST:event_btnThemActionPerformed
    private int laySoLuongTonTheoMaLK(int maLK){
        int ma=0;
        try{
            conn=KetNoiCSDL();
            String sql="select SoLuongTon from LinhKien where MaLinhKien=?";
            ps=conn.prepareStatement(sql);
            ps.setInt(1, maLK);
            rs=ps.executeQuery();
            while(rs.next()){
                ma=rs.getInt("SoLuongTon");
                return ma;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return ma;
    }
    private void truSoLuongSauKhiBan(int maLK, int soLuong){
        try{
            conn=KetNoiCSDL();
            String sql="update LinhKien set SoLuongTon=SoLuongTon-? where MaLinhKien=?";
            ps=conn.prepareStatement(sql);
            ps.setInt(1, soLuong);
            ps.setInt(2, maLK);
            ps.executeUpdate(); 
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        int rowCount = tblHoaDon.getRowCount();
        if (rowCount == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chưa thêm sản phẩm ");
            return;
        } else {
            int maNV = LayMaNhanVienTheoTen(cboTenNV.getSelectedItem().toString());
            int maKH = LayMaKhachHangTheoTen(cboTenKH.getSelectedItem().toString());
            long tongTien = tinhTongTien();
            
            for (int i = 0; i < rowCount; i++) {
                int maLK=Integer.parseInt(tblHoaDon.getValueAt(i, 1).toString());
                int soLuongBan=Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString());
                int soLuongton=laySoLuongTonTheoMaLK(maLK);
                if(soLuongBan>soLuongton){
                    JOptionPane.showMessageDialog(rootPane, "So luong ton khong du de ban: "+soLuongton);
                    return;
                }
            }
            
            themHoaDon(maKH, maNV, tongTien);
            int maHD = layMaHoaDon();
            for (int i = 0; i < rowCount; i++) {
                String tenLK = tblHoaDon.getValueAt(i, 0).toString();
                int maLK = Integer.parseInt(tblHoaDon.getValueAt(i, 1).toString());
                long giaBan = Long.parseLong(tblHoaDon.getValueAt(i, 2).toString());
                int soLuongBan = Integer.parseInt(tblHoaDon.getValueAt(i, 3).toString());
                long thanhTien = Long.parseLong(tblHoaDon.getValueAt(i, 4).toString());
                themCTHD(maHD, maLK, tenLK, giaBan, soLuongBan, thanhTien);
                truSoLuongSauKhiBan(maLK, soLuongBan);
            }
            dtm.setRowCount(0);
            txtGiaBan.setText("");
            txtMaLK.setText("");
            txtSoLuong.setText("");
            txtThanhTien.setText("");
            txtTongTien.setText("");
            JOptionPane.showMessageDialog(rootPane, "Thanh toán thành công ");
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cboTenLKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTenLKItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKItemStateChanged

    private void cboTenLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenLKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKMouseClicked

    private void cboTenLKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenLKMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKMouseEntered

    private void cboTenLKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenLKMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKMouseExited

    private void cboTenLKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenLKMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKMousePressed

    private void cboTenLKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenLKMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKMouseReleased

    private void cboTenLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenLKActionPerformed
        // TODO add your handling code here:
        // cboTenLK.setSelectedItem(cboTenLK.getSelectedIndex());
        //hienThiThongTinSauKhiChonSanPham(cboTenLK.getItemAt(cboTenLK.getSelectedIndex()));
        // HienThiCboTenLinhKien();
    }//GEN-LAST:event_cboTenLKActionPerformed

    private void cboTenLKPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboTenLKPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKPropertyChange

    private void cboTenLKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboTenLKKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenLKKeyPressed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        int row = tblHoaDon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng trong bảng để xóa");
            return;
        } else {
            dtm.removeRow(row);
            long tongTien = tinhTongTien();
            Locale VN = new Locale("vi", "VN");
            Currency dollars = Currency.getInstance(VN);
            NumberFormat VNDFormat = NumberFormat.getCurrencyInstance(VN);
            txtTongTien.setText(VNDFormat.format(tongTien));
        }
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tblHoaDon.getSelectedRow();
        txtGiaBan.setText(tblHoaDon.getValueAt(row, 2).toString());
        txtMaLK.setText(tblHoaDon.getValueAt(row, 1).toString());
        txtSoLuong.setText(tblHoaDon.getValueAt(row, 3).toString());
        txtThanhTien.setText(tblHoaDon.getValueAt(row, 4).toString());
        cboTenLK.getModel().setSelectedItem(tblHoaDon.getValueAt(row, 0).toString());

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtGiaBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiaBanMouseClicked
        // TODO add your handling code here:
        hienThiThongTinSauKhiChonSanPham(cboTenLK.getItemAt(cboTenLK.getSelectedIndex()));
        txtThanhTien.setText("");
    }//GEN-LAST:event_txtGiaBanMouseClicked

    private void txtSoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongKeyPressed

    private void cboTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cboTenKH;
    private javax.swing.JComboBox<String> cboTenLK;
    private javax.swing.JComboBox<String> cboTenNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaLK;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(() -> {
            new formBanHang().setVisible(true);
        });
    }
}
