/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author thanh
 */
public class frmMain extends javax.swing.JFrame {
    Color DefaultColor,ClickedColor;
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        DefaultColor = new Color(13,36,51);
        ClickedColor = new Color(240,151,57);
        
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanelKH = new javax.swing.JPanel();
        jLabelBH = new javax.swing.JLabel();
        jPanelBH = new javax.swing.JPanel();
        jLabelBH1 = new javax.swing.JLabel();
        jPanelNCC = new javax.swing.JPanel();
        jLabelBH2 = new javax.swing.JLabel();
        jPanelPNH = new javax.swing.JPanel();
        jLabelBH3 = new javax.swing.JLabel();
        jPanelQLPNH = new javax.swing.JPanel();
        jLabelBH4 = new javax.swing.JLabel();
        jPanelLK = new javax.swing.JPanel();
        jLabelBH5 = new javax.swing.JLabel();
        jPanelNV = new javax.swing.JPanel();
        jLabelBH6 = new javax.swing.JLabel();
        jPanelTK = new javax.swing.JPanel();
        jLabelBH7 = new javax.swing.JLabel();
        jPanelHD = new javax.swing.JPanel();
        jLabelBH8 = new javax.swing.JLabel();
        jPanelLLK = new javax.swing.JPanel();
        jLabelBH9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jDesktopPanel.setPreferredSize(new java.awt.Dimension(1390, 926));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1389, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(240, 151, 57));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jName.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jName.setText("Menu");

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/pngwing.com.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(621, 621, 621)
                    .addComponent(jLabel2)
                    .addContainerGap(622, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(17, 17, 17)))
        );

        jPanel5.setBackground(new java.awt.Color(13, 36, 51));

        jPanelKH.setBackground(new java.awt.Color(13, 36, 51));
        jPanelKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelKHMousePressed(evt);
            }
        });

        jLabelBH.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH.setText("Khách Hàng");

        javax.swing.GroupLayout jPanelKHLayout = new javax.swing.GroupLayout(jPanelKH);
        jPanelKH.setLayout(jPanelKHLayout);
        jPanelKHLayout.setHorizontalGroup(
            jPanelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKHLayout.setVerticalGroup(
            jPanelKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBH.setBackground(new java.awt.Color(13, 36, 51));
        jPanelBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBHMousePressed(evt);
            }
        });

        jLabelBH1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH1.setText("Bán Hàng");

        javax.swing.GroupLayout jPanelBHLayout = new javax.swing.GroupLayout(jPanelBH);
        jPanelBH.setLayout(jPanelBHLayout);
        jPanelBHLayout.setHorizontalGroup(
            jPanelBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBHLayout.setVerticalGroup(
            jPanelBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelNCC.setBackground(new java.awt.Color(13, 36, 51));
        jPanelNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNCCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelNCCMousePressed(evt);
            }
        });

        jLabelBH2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH2.setText("Nhà Cung Cấp");

        javax.swing.GroupLayout jPanelNCCLayout = new javax.swing.GroupLayout(jPanelNCC);
        jPanelNCC.setLayout(jPanelNCCLayout);
        jPanelNCCLayout.setHorizontalGroup(
            jPanelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNCCLayout.setVerticalGroup(
            jPanelNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNCCLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelPNH.setBackground(new java.awt.Color(13, 36, 51));
        jPanelPNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPNHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelPNHMousePressed(evt);
            }
        });

        jLabelBH3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH3.setText("Phiếu Nhập Hàng");

        javax.swing.GroupLayout jPanelPNHLayout = new javax.swing.GroupLayout(jPanelPNH);
        jPanelPNH.setLayout(jPanelPNHLayout);
        jPanelPNHLayout.setHorizontalGroup(
            jPanelPNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPNHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPNHLayout.setVerticalGroup(
            jPanelPNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPNHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelQLPNH.setBackground(new java.awt.Color(13, 36, 51));
        jPanelQLPNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQLPNHMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQLPNHMousePressed(evt);
            }
        });

        jLabelBH4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH4.setText("Quản Lý Phiếu Nhập Hàng");

        javax.swing.GroupLayout jPanelQLPNHLayout = new javax.swing.GroupLayout(jPanelQLPNH);
        jPanelQLPNH.setLayout(jPanelQLPNHLayout);
        jPanelQLPNHLayout.setHorizontalGroup(
            jPanelQLPNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLPNHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelQLPNHLayout.setVerticalGroup(
            jPanelQLPNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQLPNHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelLK.setBackground(new java.awt.Color(13, 36, 51));
        jPanelLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLKMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLKMousePressed(evt);
            }
        });

        jLabelBH5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH5.setText("Linh Kiện");

        javax.swing.GroupLayout jPanelLKLayout = new javax.swing.GroupLayout(jPanelLK);
        jPanelLK.setLayout(jPanelLKLayout);
        jPanelLKLayout.setHorizontalGroup(
            jPanelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanelLKLayout.setVerticalGroup(
            jPanelLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelNV.setBackground(new java.awt.Color(13, 36, 51));
        jPanelNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNVMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelNVMousePressed(evt);
            }
        });

        jLabelBH6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH6.setText("Nhân Viên");

        javax.swing.GroupLayout jPanelNVLayout = new javax.swing.GroupLayout(jPanelNV);
        jPanelNV.setLayout(jPanelNVLayout);
        jPanelNVLayout.setHorizontalGroup(
            jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNVLayout.setVerticalGroup(
            jPanelNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelTK.setBackground(new java.awt.Color(13, 36, 51));
        jPanelTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTKMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTKMousePressed(evt);
            }
        });

        jLabelBH7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH7.setText("Thống Kê");

        javax.swing.GroupLayout jPanelTKLayout = new javax.swing.GroupLayout(jPanelTK);
        jPanelTK.setLayout(jPanelTKLayout);
        jPanelTKLayout.setHorizontalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTKLayout.setVerticalGroup(
            jPanelTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelHD.setBackground(new java.awt.Color(13, 36, 51));
        jPanelHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHDMousePressed(evt);
            }
        });

        jLabelBH8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH8.setText("Hóa Đơn");

        javax.swing.GroupLayout jPanelHDLayout = new javax.swing.GroupLayout(jPanelHD);
        jPanelHD.setLayout(jPanelHDLayout);
        jPanelHDLayout.setHorizontalGroup(
            jPanelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHDLayout.setVerticalGroup(
            jPanelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelLLK.setBackground(new java.awt.Color(13, 36, 51));
        jPanelLLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLLKMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLLKMousePressed(evt);
            }
        });

        jLabelBH9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBH9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBH9.setText("Loại Linh Kiện");

        javax.swing.GroupLayout jPanelLLKLayout = new javax.swing.GroupLayout(jPanelLLK);
        jPanelLLK.setLayout(jPanelLLKLayout);
        jPanelLLKLayout.setHorizontalGroup(
            jPanelLLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLLKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBH9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLLKLayout.setVerticalGroup(
            jPanelLLKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLLKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBH9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelQLPNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelQLPNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanelBHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBHMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(ClickedColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Bán Hàng");
    }//GEN-LAST:event_jPanelBHMousePressed

    private void jPanelKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKHMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(ClickedColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Khách Hàng");
    }//GEN-LAST:event_jPanelKHMousePressed

    private void jPanelNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNVMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(ClickedColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Nhân Viên");
    }//GEN-LAST:event_jPanelNVMousePressed

    private void jPanelNCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNCCMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(ClickedColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Nhà Cung Cấp");
    }//GEN-LAST:event_jPanelNCCMousePressed

    private void jPanelPNHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPNHMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(ClickedColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Phiếu Nhập Hàng");
    }//GEN-LAST:event_jPanelPNHMousePressed

    private void jPanelQLPNHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLPNHMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(ClickedColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Quản Lý Phiếu Nhập Hàng");
    }//GEN-LAST:event_jPanelQLPNHMousePressed

    private void jPanelLKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLKMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(ClickedColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Linh Kiện");
    }//GEN-LAST:event_jPanelLKMousePressed

    private void jPanelHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHDMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(ClickedColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Hóa Đơn");
    }//GEN-LAST:event_jPanelHDMousePressed

    private void jPanelTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTKMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(ClickedColor);
        jPanelLLK.setBackground(DefaultColor);
        
        jName.setText("Thống Kê");
    }//GEN-LAST:event_jPanelTKMousePressed

    private void jPanelBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBHMouseClicked
        // TODO add your handling code here:
        formBanHang frmBH = new formBanHang();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmBH).setVisible(true);
    }//GEN-LAST:event_jPanelBHMouseClicked

    private void jPanelTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTKMouseClicked
        // TODO add your handling code here:
        frmThongKe frmTK = new frmThongKe();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmTK).setVisible(true);
    }//GEN-LAST:event_jPanelTKMouseClicked

    private void jPanelNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNCCMouseClicked
        // TODO add your handling code here:
        formNhaCungCap frmNCC = new formNhaCungCap();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmNCC).setVisible(true);
    }//GEN-LAST:event_jPanelNCCMouseClicked

    private void jPanelPNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPNHMouseClicked
        // TODO add your handling code here:
        formPNH frmPNH = new formPNH();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmPNH).setVisible(true);
    }//GEN-LAST:event_jPanelPNHMouseClicked

    private void jPanelQLPNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQLPNHMouseClicked
        // TODO add your handling code here:
        formQLPNH frmQLPNH = new formQLPNH();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmQLPNH).setVisible(true);
    }//GEN-LAST:event_jPanelQLPNHMouseClicked

    private void jPanelLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLKMouseClicked
        // TODO add your handling code here:
        formLK frmLK = new formLK();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmLK).setVisible(true);
    }//GEN-LAST:event_jPanelLKMouseClicked

    private void jPanelHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHDMouseClicked
        // TODO add your handling code here:
        formHD frmHD = new formHD();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmHD).setVisible(true);
    }//GEN-LAST:event_jPanelHDMouseClicked

    private void jPanelKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKHMouseClicked
        // TODO add your handling code here:
        formKhachHang frmKH = new formKhachHang();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmKH).setVisible(true);
    }//GEN-LAST:event_jPanelKHMouseClicked

    private void jPanelNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNVMouseClicked
        // TODO add your handling code here:
        formNhanVien frmNV = new formNhanVien();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmNV).setVisible(true);
    }//GEN-LAST:event_jPanelNVMouseClicked

    private void jPanelLLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLLKMouseClicked
        // TODO add your handling code here:
        formLoaiLinhKien frmLLK = new formLoaiLinhKien();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(frmLLK).setVisible(true);
    }//GEN-LAST:event_jPanelLLKMouseClicked

    private void jPanelLLKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLLKMousePressed
        // TODO add your handling code here:
        jPanelBH.setBackground(DefaultColor);
        jPanelKH.setBackground(DefaultColor);
        jPanelNV.setBackground(DefaultColor);
        jPanelNCC.setBackground(DefaultColor);
        jPanelPNH.setBackground(DefaultColor);
        jPanelQLPNH.setBackground(DefaultColor);
        jPanelLK.setBackground(DefaultColor);
        jPanelHD.setBackground(DefaultColor);
        jPanelTK.setBackground(DefaultColor);
        jPanelLLK.setBackground(ClickedColor);
        
        jName.setText("Loại Linh Kiện");
    }//GEN-LAST:event_jPanelLLKMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBH;
    private javax.swing.JLabel jLabelBH1;
    private javax.swing.JLabel jLabelBH2;
    private javax.swing.JLabel jLabelBH3;
    private javax.swing.JLabel jLabelBH4;
    private javax.swing.JLabel jLabelBH5;
    private javax.swing.JLabel jLabelBH6;
    private javax.swing.JLabel jLabelBH7;
    private javax.swing.JLabel jLabelBH8;
    private javax.swing.JLabel jLabelBH9;
    private javax.swing.JLabel jName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBH;
    private javax.swing.JPanel jPanelHD;
    private javax.swing.JPanel jPanelKH;
    private javax.swing.JPanel jPanelLK;
    private javax.swing.JPanel jPanelLLK;
    private javax.swing.JPanel jPanelNCC;
    private javax.swing.JPanel jPanelNV;
    private javax.swing.JPanel jPanelPNH;
    private javax.swing.JPanel jPanelQLPNH;
    private javax.swing.JPanel jPanelTK;
    // End of variables declaration//GEN-END:variables
}
