/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Vector;
import static javafx.scene.input.KeyCode.X;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class frmThongKe extends javax.swing.JInternalFrame {
    public Connection conn;
    public   PreparedStatement ps=null;
    public   ResultSet rs=null;
    DefaultTableModel dtmHD;
    
    /**
     * Creates new form frmThongKe
     */
    public frmThongKe() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI UI=(BasicInternalFrameUI)this.getUI();
        UI.setNorthPane(null);
        dtmHD=(DefaultTableModel) jTableHoaDon.getModel();
        hienThiTableHoaDon();
        Tong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHoaDon = new javax.swing.JTable();
        jLabelTongDoanhThu = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1396, 928));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setText("THỐNG KÊ DOANH THU");

        jTableHoaDon.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày xuất hóa đơn", "Thành tiền"
            }
        ));
        jTableHoaDon.setRowHeight(40);
        jScrollPane1.setViewportView(jTableHoaDon);

        jLabelTongDoanhThu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTongDoanhThu.setText("TỔNG DOANH THU :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 884, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTongDoanhThu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHoaDon;
    // End of variables declaration//GEN-END:variables

    public Connection KetNoiCSDL(){
        String user="sa";
        String pass="123456";
        try{
            conn=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLLinhKienPC_Laptop_java",user,pass);
            
            return conn;
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        return conn;
    }
    
    private void hienThiTableHoaDon() {
        try {
            dtmHD.setRowCount(0);
            conn=KetNoiCSDL();
            String sql="select MaHoaDon,NgayXuatHoaDon,Tongtien\n" +
                        "from HOADON \n";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                Vector<Object> vec=new Vector<>();
                vec.add(rs.getInt("MaHoaDon"));
                vec.add(rs.getDate("NgayXuatHoaDon"));
                vec.add(rs.getLong("Tongtien"));
                dtmHD.addRow(vec);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(() -> {
            new frmThongKe().setVisible(true);
        });
    }

    private void Tong() {
        DecimalFormat x= new DecimalFormat("###,###,###");
        int tong = 0;
        for (int i = 0; i < jTableHoaDon.getRowCount(); i++) {
            tong += Integer.parseInt(jTableHoaDon.getValueAt(i, 2).toString());
        }
        jLabelTongDoanhThu.setText("TỔNG DOANH THU :"+ " " + x.format(tong)+ " " + "VND");
    }
}
